### PR TITLE
Added dry run option + script refactor

### PR DESCRIPTION
**Pull request by ilteoood**

### CODE REVIEW

**Comment by diegoveloper** [comment]
Any news about this PR?  @ilteoood can we use your git repo directly ?

**Comment by ilteoood** [comment]
@diegoveloper hi, yes you can use directly the code in my branch.
I think that the maintainer isn't active now on github...

**Comment by diegoveloper** [comment]
Great! do you know how I can point directly to your repo ?

**Comment by ilteoood** [comment]
@diegoveloper you can simply point to: ilteoood/actions-flutter-pub-publisher:master

**Comment by diegoveloper** [comment]
@ilteoood I got this error :

```
- Your workflow file was invalid: The pipeline is not valid. .github/workflows/dev.yml (Line: 16, Col: 15): Expected format {org}/{repo}[/path]@ref. Actual 'ilteoood/actions-flutter-pub-publisher:master',Input string was not in a correct format.

```

This is how I used your config:

```
jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dry-run
        uses: ilteoood/actions-flutter-pub-publisher:master
        with:
          credential: ${{secrets.CREDENTIAL_JSON}}
          flutter_package: false
          skip_test: true
          dry_run: true
```

Any idea?

**Comment by ilteoood** [comment]
@diegoveloper sorry, I made a typo: istead of ":master", use "@master"

**Comment by diegoveloper** [comment]
@ilteoood thank you, it's working :)

**Comment by sakebook** [comment]
@ilteoood 

Sorry for the delay in replying!

Thanks for the refactoring!

LGTM.

**Pull request merged**
